{% include 'misc/header.py' %}
version: '2.3'
services:
  cache:
    extends:
      file: docker-services.yml
      service: cache
{%- if cookiecutter.database != 'sqlite'%}
  db:
    extends:
      file: docker-services.yml
      service: db
{%- endif %}
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es
